/** Shared FAQ copy — used by PageClient UI and JSON-LD. Matched to LIVE. */
export const faqs = [
  { q: "How do I sell my home for cash?", a: "You can sell your home for cash by contacting a cash-buying company, investor, or iBuyer, or by attracting a cash buyer through a traditional listing. The buyer reviews your property, makes a no-obligation offer (often within 24–48 hours), and closes through a title company — sometimes in as little as 7 to 14 days, since no mortgage financing is involved. Before choosing, it's wise to compare the cash offer against listing on the open market to see which nets you more." },
  { q: "Who pays cash for houses in Arizona?", a: "Cash for houses in Arizona typically comes from real estate investors, \"We Buy Houses\" companies, and iBuyers. They buy quickly and often as-is, but usually pay below full market value in exchange for speed and convenience. Mortgage Brothers LLC does not buy houses — as independent mortgage experts, we help you compare those cash offers against your other options at no cost." },
  { q: "Is selling a house for cash a good idea?", a: "It can be — when speed and certainty matter more than maximizing price. A cash sale skips repairs, showings, and financing delays. But because cash offers are often lower, it isn't automatically the best financial choice. Comparing a cash offer to a traditional or as-is sale is the only way to know what's right for your situation." },
  { q: "How much less do cash buyers pay?", a: "It varies widely by buyer and property condition. Investor and \"We Buy Houses\" offers generally come in below full market value, because the buyer factors in repairs, holding costs, and profit; iBuyers often pay closer to market value but charge a service fee. Because there's no fixed number, the only reliable way to know what an offer is really worth is to compare it against what your home would bring on the open market." },
  { q: "Can I sell my house as-is?", a: "Yes. Many Arizona homeowners sell as-is without making repairs, either to a cash buyer or through an agent. Selling as-is saves time and money on repairs, though the price you receive may be lower than for a move-in-ready home." },
  { q: "What are the risks of cash buyers?", a: "The main risks are offers well below market value, high-pressure tactics, and buyers with no verifiable track record. Protect yourself by checking reviews, confirming the buyer can actually fund the purchase, closing through a licensed Arizona title company, and comparing the offer to your other options first." },
  { q: "How fast can a cash sale close?", a: "Cash sales can often close in as little as 7 to 14 days, depending on the buyer, title work, and required documentation — much faster than a typical financed sale that takes 30 to 60 days." },
  { q: "Should I accept a cash offer?", a: "Only after you've compared it to your alternatives. A cash offer is worth accepting when its speed and convenience outweigh the lower price for your specific goals and timeline. Our free Home Selling Options Review lays the numbers side by side so you can decide with confidence." },
];

export const faqSchemaItems = faqs.map((item) => ({
  question: item.q,
  answer: item.a,
}));
