/** Shared FAQ copy — used by PageClient UI and JSON-LD. Matched to LIVE. */
export const faqs = [
  { q: "Do Closing Costs Include the Down Payment?", a: "Why do homebuyers often conflate down payments with **closing costs**? Both represent essential financial elements during a home purchase, creating confusion between the two. However, they serve very different purposes. A **down payment** is the buyer's equity contribution toward purchasing the home itself, typically ranging from 3% to 20% of the property's purchase price. Closing costs, on the other hand, cover fees associated with finalizing the real estate transaction, and generally amount to 1.5%–3% of the home's purchase price. To clarify further, consider the following distinctions: Down payments build equity; Closing costs are transactional fees; Down payments influence loan amount; Closing costs cover lender and title fees, taxes, and prepaid expenses; Both must be budgeted separately when planning to purchase a home." },
  { q: "Does Paying Closing Costs Affect Your Mortgage Payment?", a: "Although **closing costs** are traditionally paid upfront at the time of purchasing a home, some buyers choose to finance these costs into their mortgage, impacting the **loan terms** and ultimate repayment schedule. When closing costs are paid upfront, the buyer benefits from a **reduced total loan amount**, consequently lowering both the loan's principal and overall interest charges across its lifespan. Alternatively, financing closing costs into the mortgage increases the loan's size, resulting in **higher monthly payments**, due to **additional borrowed funds** accruing interest. For example, financing approximately $5,000 in closing expenses into a 30-year mortgage, at a 6% interest rate, could add roughly $30 per month to mortgage payments. Understanding these financial implications allows homebuyers to make **informed decisions** aligned with their financial goals." },
  { q: "How Can You Pay for Closing Costs?", a: "When preparing to cover **closing costs**, homebuyers have several practical options available, including **personal savings**, **lender credits**, or specialized **assistance programs**. Personal savings allow immediate payment without additional obligations, offering the simplest solution for those who have budgeted carefully. Lender credits can reduce upfront costs; however, this usually comes with slightly higher interest rates over the mortgage term. Specialized assistance programs like Home+Plus or Pathway to Purchase can offer grants covering up to 5% and 10%, retrospectively and subjected to change, of loan amounts, beneficial for buyers requiring **financial support**. Considerations for covering closing costs include: Using personal savings to minimize long-term debt; Employing lender credits, understanding this may impact mortgage interest rates; Applying for state or local housing grants; Pursuing forgivable loans provided for qualified buyers; Negotiating costs with the seller directly. > Understanding **closing costs**—and accurately estimating them through a **reliable calculator**—is essential for any homebuyer aiming for a stress-free purchase. Familiarity with **typical closing fees**, financing options, and market dynamics provides buyers with valuable tools to **manage these expenses** effectively. By proactively implementing strategies to reduce costs and adequately preparing their budgets, buyers can confidently navigate the complexities of real estate transactions, ensuring a smoother, more transparent, and financially informed home-buying experience. You've explored every angle of closing costs—now let's put that knowledge into action. Reach out for your free, personalized closing cost estimate and expert guidance. Request Your Free Estimate" },
];

export const faqSchemaItems = faqs.map((item) => ({
  question: item.q,
  answer: item.a,
}));
